### ISSUE TITLE
About the training dataset

### ISSUE THREAD

**Issue by suweisuwei11** [chunbolang/BAM#10]
Hello, I think your work is very interesting, but I observed that you re-screened the training samples of each subset, how did you filter the training samples.

**Comment by chunbolang** [comment]
Hi,
thanks for your interest!

I'm not sure if you are referring to this part of the [code](https://github.com/chunbolang/BAM/blob/main/util/dataset.py#L164-L170). Running the uncommented code could produce the list we use.

Feel free to contact.

**Comment by suweisuwei11** [comment]
Hello, this code is the same as PFENET, we use this code to get the training set list. But comparing the two training sets we find that each subset lacks a different number of training samples.

**Comment by chunbolang** [comment]
The code [here ](https://github.com/chunbolang/BAM/blob/main/util/dataset.py#L59-L67) leads to the difference in the number of training samples. I was trying to remove the images containing the _novel_ class in the meta-training phase to prevent potential information leakage. 

But from what I've observed, this has very little impact on performance. Therefore, you can also use the list of PFENet, that is, set `filter_intersection=False` (check [here](https://github.com/chunbolang/BAM/blob/main/util/dataset.py#L166)).
