### ISSUE TITLE
Tensorboard

### ISSUE THREAD

**Issue by Ehteshamciitwah** [chunbolang/BAM#12]
Hello, 
Congratulations on the acceptance of your paper as an Oral Presentation.
I just want to track training using a tensorboard. Although you are using SummaryWriter for the tensor board, can you elaborate how can I track the training on the tensorboard.

**Comment by chunbolang** [comment]
Hi,
you can add `--viz` argument to the script [here](https://github.com/chunbolang/BAM/blob/main/train.sh#L24), then the corresponding _log_ files will be saved in the `/BAM/split*/net*/result` folder.

Regards,
Chunbo
