### ISSUE TITLE
Training BAM

### ISSUE THREAD

**Issue by Ehteshamciitwah** [chunbolang/BAM#14]
Hello,

I am training BAM using resnet50 on pascal 0 fold. But Miou is still zero after 7 epochs.

![image](https://user-images.githubusercontent.com/79190474/161901172-212988e7-65c3-429b-8d74-381b0dde2f71.png)

**Comment by chunbolang** [comment]
Hi,
Have you _pre-trained_ the base learner or directly use the model we provide?
Also, I didn't pay much attention to the metrics during training, maybe you can let the model warm-up for a while.

**Comment by Ehteshamciitwah** [comment]
I am using provided base learner model. However, I am still training and will update you about my progress.

**Comment by chunbolang** [comment]
Hi, 
you could refer to our log file of the experiment on _pascal-0 using resnet50_ [here](https://mailnwpueducn-my.sharepoint.com/:u:/g/personal/langchunbo_mail_nwpu_edu_cn/ERNSLRacF-hHtNfXK1WqdEYBxwUNGsTEv2fSSyKmqRUSbg?e=xya86L).

**Comment by Ehteshamciitwah** [comment]
Thank you very much.

**Comment by Ehteshamciitwah** [comment]
Hi,
 Results are good for fold 0 of pascal. However, while training on Fold1, the val-Mean IoU of meta is higher than the final. What is the relation between final and Meta Mean IoU.  does ensemble always increase meta Mean IoU or some time it will decrease the meta output? 
for fold0 val-meta = 63-65 and val-final =66-68 and base=34 constant
while for fold 1 val-meta = 68-72  val-final =60-67 and base= 30 constant

**Comment by chunbolang** [comment]
Hi,
the mIoU results of _final_ should be larger than that of _meta_. 
And there was no case of _meta_ being larger than _final_ during my training/testing.

Besides, what does `val-final=60-67`  represent?

Regards,

**Comment by Ehteshamciitwah** [comment]
Hello, 
sorry for the delay. Val-final means the range of final Miou. 
To achieve BAM results, I just want to know which config file parameters affect the MIoU. 
fix_bn = true vs false 
zoom factor etc. Thank you

**Comment by chunbolang** [comment]
Is there such a big fluctuation in the results you reproduce, 60~67?
`batch_size` and `fix_bn` affect the mIoU; the former has a greater impact.

Other researchers seem to have successfully reproduced results based on this repo, maybe you could check the dataset used.

**Comment by Ehteshamciitwah** [comment]
Thank you .

**Comment by caoql98** [comment]
I have the same question. The Miou is zero during the training. Could you tell me how do you solve the problem?
