### ISSUE TITLE
Evaluation on another dataset

### ISSUE THREAD

**Issue by Genj1** [chunbolang/BAM#15]
Hello,

Thanks for your great job!
I want to use the model trained on Pascal Dataset and evaluate on my own dataset. So how to do that? Change the dataset to 
Pascal-format ？

Would you please give me some suggestions?

Best wishes to you!

**Comment by chunbolang** [comment]
Hi,
thanks for your interest!

Yes, you just need to modify the `_get_item_()` function in the dataset, _i.e.,_ specifying the path of the image and mask. 

Regards,
Chunbo
