### ISSUE TITLE
Use of adjustment factor

### ISSUE THREAD

**Issue by alpoler** [chunbolang/BAM#16]
In paper, there are no clear explanation of how adjustment factor is utilized to affect meta prediction so I inspect your code to make sense of how you include it in your model. I realized that you concatenate frobenius norm of difference between gram matricies and meta prediction of foreground or background and process this map with shared 1 by 1 convolution. Is there any reason of initializing with specifically with 1 0 ? @chunbolang

**Comment by chunbolang** [comment]
Such an initialization approach is similar to a warm-up strategy, whereby the base-learner is introduced to provide additional guidance when the meta-learner has a certain level of competence.

**Comment by alpoler** [comment]
In paper, you mention filtering of meta prediction with the guidance of the adjustment factor as Fψ((p0_m). In fact, you apply convolution over concatenation of meta background prediction and the norm of gram matricies differences in the code as F_1x1(cat(p0_m,ψ)). When I read paper first time, I thought that meta-prediction values are multiplied with constant of adjustment only. @chunbolang

**Comment by chunbolang** [comment]
Everyone interprets the content differently, so we release the code. Sorry for the inconvenience.
