### ISSUE TITLE
Performance of Base Learner

### ISSUE THREAD

**Issue by alpoler** [chunbolang/BAM#17]
Hello @chunbolang,

 You share model belonging to base learner without mIoU results on 16 classes for 4-fold. Would you share this evaluation result for base learner ? I want to check whether or not it results as same accuracy as my reproduced experiments in pretraining case. Thank you in advance.

**Comment by chunbolang** [comment]
@alpoler 
Hi,
I did not actually pay much attention to the performance of the base learner and just reproduced it based on the [RePRI](https://github.com/mboudiaf/RePRI-for-Few-Shot-Segmentation). The results are tabulated as follows:

| PASCAL | P-0 | P-1 | P-2 | P-3 |
| ----- | ----- | ----- | ----- | ----- |
| VGG16 | 67.76 | 65.82 | 65.51 | 69.95 |
| Res50 | 71.43 | 69.17 | 69.19| 73.72 |

| COCO | C-0 | C-1 | C-2 | C-3 |
| ----- | ----- | ----- | ----- | ----- |
| VGG16 | 44.99 | 43.04 | 45.92 | 45.05 |
| Res50 | 50.84 | 49.41 | 51.95| 50.89 |

Regards,
