### ISSUE TITLE
Dataset Difference 

### ISSUE THREAD

**Issue by Ehteshamciitwah** [chunbolang/BAM#18]
Hello,

During the training of your model. I realized the model is using nearly 4000+ images for training on PASCAL fold0. While the other comparable models like HSNET/PPM are using different lists containing nearly 11000 images for fold 0. Why there is a difference between training images number. am I missing something?

**Comment by chunbolang** [comment]
Hi,
please check the similar [issue](https://github.com/dvlab-research/PFENet/issues/13) raised in PFENet repo.

**Comment by Ehteshamciitwah** [comment]
Thank you for your quick response. I understand that PFENet/BAM is using a training set after excluding validation images and it contains a different list than PANEt and HSnet. 
But during comparison of MIoU is it fair to compare when models are trained on different numbers of images?

**Comment by chunbolang** [comment]
Compared to PFENet, we removed the _base_ class training images containing _novel_ objects, as this [line](https://github.com/chunbolang/BAM/blob/main/util/dataset.py#L166). However, such an operation had little impact on performance. 
We argue that more training samples may slightly improve but with a larger computational burden. Of course, you can also use the 1w+ images for training like HSNet.

**Comment by Ehteshamciitwah** [comment]
Thank you very much.
