### ISSUE TITLE
Dataset path problem

### ISSUE THREAD

**Issue by szxmachinelearning** [chunbolang/BAM#19]
Hello, I would like to ask where should my dataset be placed?

**Comment by chunbolang** [comment]
Hi, 
Please refer to the link below to build the dataset.
https://github.com/chunbolang/BAM/blob/main/util/get_mulway_base_data.py#L29

**Comment by szxmachinelearning** [comment]
Thank you for your reply.But I want to know why my downloaded dataset doesn't have 'SegmentationClassAug' folder
![12(O09YDKGVM%FP {6(`{{P](https://user-images.githubusercontent.com/43338998/166223901-e6cb4e8a-d74f-4a56-9235-676a75b5dbb7.png)
Good luck！

**Comment by szxmachinelearning** [comment]
作者您好，我在测试时，1-shot改成5-shot后，报了模型相关的错误，由于刚接触这个方向，所以不太懂，1-shot和5-shot是需要不同的模型吗？

**Comment by chunbolang** [comment]
感谢您对我们工作的关注！

我们在5-shot设置下引入了额外的reweighting策略，参考这段[代码](https://github.com/chunbolang/BAM/blob/main/model/BAM.py#L119-L128)，因此直接使用1-shot模型会报错。
您需要重新训练5-shot模型，或者简单地将这部分参数设置为[相等权重](https://github.com/chunbolang/BAM/blob/main/model/BAM.py#L123)。

P.S.: 使用1-shot模型进行5-shot推理对于部分方法是可行的，如PFENet，但单独训练5-shot模型似乎可以取得更好的性能。

**Comment by szxmachinelearning** [comment]
好的，感谢！
