### ISSUE TITLE
请问作者可以提供完整的预训练模型吗？

### ISSUE THREAD

**Issue by dizzygithub** [chunbolang/BAM#20]
首先，感谢作者们很棒的工作。我看到作者们只是提供了部分BAM的预训练模型。作者能不能将文章中的pascal、coco表格中发布的结果对应的预训练模型完整公开啊？这样很方便快速验证且复线作者的结果。

**Comment by chunbolang** [comment]
没有问题~
抱歉目前正忙于其他项目，我们会争取在下周末之前提供完整的模型。
目前您可以直接加载所提供的base learner权重，在此基础上训练自己的meta learner。

**Comment by dizzygithub** [comment]
感谢作者的回复，期待作者上传完整的结果论证。

**Comment by chunbolang** [comment]
完整的训练模型已经上传，请查看[链接](https://mailnwpueducn-my.sharepoint.com/:f:/g/personal/langchunbo_mail_nwpu_edu_cn/ElxMt3Mr9xBMr41BrOOE5JABEVnJ5f9-SVBRutEhpY3vxg?e=upF3mf)。
