### ISSUE TITLE
Paper reproduction

### ISSUE THREAD

**Issue by AI-student-wl** [chunbolang/BAM#21]
Hello, thank you for your excellent work. I'm reproducing the results. First, I ran get_ mulway_ base_ data. Py file, the corresponding train and val data are obtained: 0, 1, 2, 3.
I finished running train_ base. SH file to get Figure 1
![11](https://user-images.githubusercontent.com/72002667/168414202-26261fa0-34f3-4462-9d2e-ba0a8578828b.png)
Then run train SH, but 75 epoch is still 0, as shown in Figure 2
![22](https://user-images.githubusercontent.com/72002667/168414205-d75a857d-15e4-4bd5-a04e-36627966dd84.png)

What is the reason

**Comment by chunbolang** [comment]
Hi,
Please make sure that the trained base model is saved under the right directory, as shown below:
https://github.com/chunbolang/BAM/blob/main/model/BAM.py#L62

**Comment by AI-student-wl** [comment]
Thank you for your help. I have reproduced the results. Now I want to use my own data set, but I encounter these problems.
1. I change yaml's classes to 2 and start train SH successfully reproduced the result. Why change it to 2.
2. My data classification is: 1, 2, 3. sub_ list=[1, 2],  sub_ val_ List = [3], which parameter values of yaml file need to be modified, such as classes
Sorry to disturb your life. Thank you for your help

**Comment by chunbolang** [comment]
1. args.classes=2 indicates the _fg-bg_ (binary) segmentation task.
2. In your case, modifying the `config` file is not mandatory; you need to update the [list](https://github.com/chunbolang/BAM/blob/main/util/dataset.py#L114) and relevant [paths](https://github.com/chunbolang/BAM/blob/main/util/dataset.py#L110) in the `dataset.py` file .  Before this, please make sure that you have established a PASCAL-like dataset containing `img` and corresponding `mask`.
3. Furthermore, you need to refer to this [code](https://github.com/chunbolang/BAM/blob/main/util/dataset.py#L164-L198) to generate the `.txt` files specific to your dataset.  An alternative is to comment out the [L172-198](https://github.com/chunbolang/BAM/blob/main/util/dataset.py#L172-L198) of code and keep only the [L164-170](https://github.com/chunbolang/BAM/blob/main/util/dataset.py#L164-L170).

**Comment by AI-student-wl** [comment]
Thank you for your reminder. My data set has been started. At present, the training effect is good. Thank you again for your help. If I encounter new problems, I'll contact you again. I wish you a happy life

**Comment by AI-student-wl** [comment]
Hello, I updated the list, train_ base. SH finished running, but I ran train SH has encountered a new problem. My dataset mask category: [1], [1, 2], [2], [2, 3], [1, 2, 3], [3].
This is my self sub_ val_ list=[3]，self. sub_ List = [1, 2], the code will report an error when it runs to the location of the screenshot. According to this logic, only the mask of 3 cannot be added to the list, so there is an error in displaying assert len (label_class) > 0. How can I solve this problem，Trouble you again
![image](https://user-images.githubusercontent.com/72002667/168732873-951db535-6154-49bf-a2d3-508b79e13f64.png)

**Comment by chunbolang** [comment]
Under the current setting (_i.e._, self.sub_ val_ list=[3], self. sub_ List = [1, 2]),
I think the `make_dataset` function will filter the images that contain **only** category 3 (see [here](https://github.com/chunbolang/BAM/blob/main/util/dataset.py#L61-L62)), so please check that the derived `self.data_list` is correct.
