### ISSUE TITLE
Question about the pre-training?

### ISSUE THREAD

**Issue by XiaoBuL** [chunbolang/BAM#22]
Hello, thanks for your great work! 
But I have some question about the pre-training: **Does the novel class is seen as the background class when training the base-learner, which means that it is possible to train a black mask image in specific iteration?**

**Comment by chunbolang** [comment]
Hi, thanks for your attention!

This is a very insightful question that has been also raised by other researchers, referring to this [issue](https://github.com/chunbolang/BAM/issues/7#issuecomment-1078563723). 
We'd love to explore it further, so please be patient.

**Comment by XiaoBuL** [comment]
Ok! Thanks for your instant reply!
