### ISSUE TITLE
怎么样将代码设置成单卡运行呢

### ISSUE THREAD

**Issue by shiyi0306** [chunbolang/BAM#23]
作者你好!我在用单卡3080Ti运行实验的时候遇见了,显存泄漏的问题,请问您有在单卡运行的经验么,或者说这个如果改的话需要改哪里呢?期待您的回复!  祝您生活愉快!  还有您的每个阶段的运行时间可以说一下么?

**Comment by chunbolang** [comment]
您好，感谢对我们工作的关注！

I. 显存问题可以通过调小`batch_size`或降低图像分辨率的方式改善，但会在一定程度上影响结果。另，可以使用梯度累积的方式提高batch大小，例如bs=4推理但迭代两次再更新权重，即bs=8。

II. 我们在2080Ti GPU上进行了本文的实验。
训练base learner: 2GPUs。此外Res101需要>2GPUs

|  | PASCAL | COCO |
|  ----  | ----  | ----  |
| VGG  | 6h | 17h |
| Res50  | 11h | 36h |

训练meta learner, 1GPU (1-shot) or 4GPUs (5-shot)
|  | PASCAL-1shot | PASCAL-5shot |
|  ----  | ----  | ----  |
| VGG  | 6~10h | 11~24h |
| Res50 | 11~16h | 19~37h |

COCO由于训练时间较长且部分模型中断后继续训练resume，因此没有完全统计。
