### ISSUE TITLE
base_annotation

### ISSUE THREAD

**Issue by X-Hang** [chunbolang/BAM#26]
Very thanks for your great work.There is an operation like this in your work:“Run util/get_mulway_base_data.py to generate base annotations for stage1, or directly use the trained weights.”.But i run this code failed.So can you share the base_annotation?

--Thank you so much for your reply !!!

**Comment by chunbolang** [comment]
Hi, thanks for your interest!

We provide the generated base annotations, please check this [link](https://mailnwpueducn-my.sharepoint.com/:f:/g/personal/langchunbo_mail_nwpu_edu_cn/Eg7-69tgeE5Em5jEHUyvafEBA9Gj9ZCtCNV-N8rtcxySKg?e=dFvKW5).

Regards,
