### ISSUE TITLE
Results are able to reproduce

### ISSUE THREAD

**Issue by zhouyuan888888** [chunbolang/BAM#3]
Very nice job !!! I am very in interested in your work. But It seems that I cannot reproduce your results, just as presented below
![image](https://user-images.githubusercontent.com/41813767/159151373-f8162853-0c0b-4a9d-8fee-70451184946e.png)
what is wrong I have done? 

--Thank you so much for your help!!! ^_^

**Comment by chunbolang** [comment]
@zhouyuan888888 
Hi, thanks for your interest in our work!

Did you download all the _weights_ we trained and modify the corresponding _config_ file? 
Take **coco_1-shot_res50** as an example, 
- you should first put the trained weights under `BAM/exp/coco/BAM/split0/resnet50/snapshot/train_epoch_43.5_0.4341.pth`. Note that run `test.sh` except for the [last line](https://github.com/chunbolang/BAM/blob/main/test.sh#L22-L25) could facilitate folder creation. 
- Then, change the [weight](https://github.com/chunbolang/BAM/blob/main/config/coco/coco_split0_resnet50.yaml#L64-L65) as `train_epoch_43.5_0.4341.pth`.

Make sure you get a successful loading prompt from the code [here](https://github.com/chunbolang/BAM/blob/main/test.py#L83).

Besides, I have just reproduced our **pascal_1-shot_vgg** results (63.18 in our paper) on another machine, as follows:
![image](https://user-images.githubusercontent.com/41976180/159154171-42e08648-db0d-4dab-9c10-7a4e8c429848.png)

Please feel free to contact us!

Regards,
Chunbo
