### ISSUE TITLE
关于data_list和sub_class_file_list

### ISSUE THREAD

**Issue by Superwen1017** [chunbolang/BAM#31]
您好！非常感谢你们的工作，很有启发！在复现你们代码的时候我有两个问题想向您请教一下
1. 对于PASCAL-5i数据集包括VOC2012和SBD，VOC2012数据集已经下载，而SBD这部分对应的网站我们下载了benchmark.tgz，但没有看懂要怎么处理，我们在另一个网站下载了SegmentationClassAug.zip，然后可以运行。这个是SBD部分正确的处理方式吗？

2. 您提供的fss_list中的data_list和sub_class_file_list分别是怎么来的呢，有对应处理这部分的代码吗？

谢谢！盼回复！

**Comment by chunbolang** [comment]
您好，感谢关注！

1.  是的，SBD数据集提供了额外的分割掩码标注`.png`
2.  每次训练/测试都需要一个构建数据集的[过程](https://github.com/chunbolang/BAM/blob/main/util/dataset.py#L164-L170)（特别是在coco上花费时间较久），因此我们将相关数据保存便于后续直接读取使用，参考这部分[代码](https://github.com/chunbolang/BAM/blob/main/util/dataset.py#L179-L186)。
