### ISSUE TITLE
Some questions about paper

### ISSUE THREAD

**Issue by 66Kevin** [chunbolang/BAM#35]
Hi, Chunbo.
首先，非常感谢您与团队杰出的贡献。有几个关于论文的问题想请教一下，
1. 为什么不加入Base-Learner也会有大幅的提升？仅仅是因为meta-learner使用了PSPNet从base class中预训练得到的encoder吗
2. 在Ensemble module中您使用了两张特征图gram matrix之差的F范数当作调整因子，然后把meta bg与F范数map按照channel方向concat之后进行卷积。请问F范数map在这里起到什么作用，为什么该做法可以抑制base class的虚假激活区域？

Best wishes,
Yueyi Wang

**Comment by chunbolang** [comment]
您好，首先非常感谢关注~

1. 是的，相比分类网络在imagenet上的预训练参数，分割网络(base-learner)的encoder参数更适用当前FSS任务。更进一步讲，原始的encoder，也就是ResNet前4个block，其提取的特征并没有那么的"泛化"。
2. F范数是为了获得一个用于衡量差异性的"整体"指标。调节因子\psi是根据输入图像对的差异性来调整模型集成时的权重，该做法对抑制错误激活区域只起辅助作用。即使去掉这个map，仅对两个学习者级联后的特征进行卷积同样提升明显，这才是抑制虚假激活的主要来源——带有特定初始参数的卷积(全连接)层用于模型融合。

祝好，

**Comment by 66Kevin** [comment]
> 您好，首先非常感谢关注~
> 
> 1. 是的，相比分类网络在imagenet上的预训练参数，分割网络(base-learner)的encoder参数更适用当前FSS任务。更进一步讲，原始的encoder，也就是ResNet前4个block，其提取的特征并没有那么的"泛化"。
> 2. F范数是为了获得一个用于衡量差异性的"整体"指标。调节因子\psi是根据输入图像对的差异性来调整模型集成时的权重，该做法对抑制错误激活区域只起辅助作用。即使去掉这个map，仅对两个学习者级联后的特征进行卷积同样提升明显，这才是抑制虚假激活的主要来源——带有特定初始参数的卷积(全连接)层用于模型融合。
> 
> 祝好，

非常感谢您详细的回复，期待您与团队接下来的优秀工作。

Best regards,
