### ISSUE TITLE
Question about Gram matrix

### ISSUE THREAD

**Issue by 66Kevin** [chunbolang/BAM#36]
Hi Chunbo,

不好意思再次打扰，想请教几个关于ensemble module的问题
1. 由于meta-learner接收support与query两种图片的输入，所以meta-learner容易受到support图片的干扰(敏感性)，从而对部分区域产生错误预测。Ensemble module主要目的有两个：1. 通过调整因子抑制meta-learner预测图中错误激活的部分；2. 通过1x1卷积的方式融合base和meta learner的输出。请问对于Ensemble module的功能理解是否有误？
2. 支持图像和查询图像差异越大，其Gram矩阵差值的F1范数越大，对应的调整因子应该越大，为什么调整因子会减小Meta Learner预测图像的权重呢？换句话说，当差异越大(调整因子越大)时Meta-learner的输出结果越不可靠，此时不是应该给予一个较小的调整因子来减小权重吗

Best wishes,
Yueyi Wang

**Comment by chunbolang** [comment]
1. 调整因子可以从整体上调节meta-learner的预测，也就是改变置信度，并不能够具体到"错误激活的部分"。
2. 因为调整因子与meta-learner的融合过程可能会学习到负相关特性，对应"调整因子越大，meta权重越小"，不过我们并没有显式约束这一点。

祝好，

**Comment by 66Kevin** [comment]
> 1. 调整因子可以从整体上调节meta-learner的预测，也就是改变置信度，并不能够具体到"错误激活的部分"。
> 2. 因为调整因子与meta-learner的融合过程可能会学习到负相关特性，对应"调整因子越大，meta权重越小"，不过我们并没有显式约束这一点。
> 
> 祝好，

感谢您的解答！

祝好，
