### ISSUE TITLE
预训练模型下载失败

### ISSUE THREAD

**Issue by J-JunChen** [chunbolang/BAM#37]
你好啊！
     感谢你杰出的工作！我在复现的过程中，遇到无法下载 base network 的预训练模型，可能是网络阻塞的原因，往往在中途下载中断，请问你可以提供百度云盘的链接吗？非常感谢 :）

**Comment by chunbolang** [comment]
您好！
感谢关注，百度网盘链接如下：

```
链接：https://pan.baidu.com/s/1ZMYurl3-wGYYZFzpNMKrKw 
提取码：9yw6
```

**Comment by J-JunChen** [comment]
Thanks
