### ISSUE TITLE
cls_type='Base' or 'Novel'?

### ISSUE THREAD

**Issue by endeavorman** [chunbolang/BAM#40]
Thanks for your work.
When you create the model, you use code like this, model = eval(args.arch).OneModel(args, cls_type='Base').  
I want to know when to use 'Base' and when to use 'Novel'.

**Comment by chunbolang** [comment]
Hi, thanks for your interest!

You can **ignore** it. This parameter is used to determine the `meta-finetuning phase` and the `meta-testing phase`, this work does not involve the former.

Regards,
Chunbo

**Comment by endeavorman** [comment]
thanks for your reply.
