### ISSUE TITLE
Train and infer with higher number of images? k-shot with higher k?

### ISSUE THREAD

**Issue by hazkaz** [chunbolang/BAM#41]
Thank you for sharing your work!

Is it possible to train and run inference with k-shot where k is higher such as say 10, 50 or 100? What are the limitations or possible modifications for this?

Thanks.

**Comment by chunbolang** [comment]
Hi, thanks for your interest!

You can directly modify the "shot" argument in the `config` file for training and testing.
However, in my opinion, the **fine-tuning** strategy might yield better performance if more than **30** labeled samples are available.

Regards,

**Comment by hazkaz** [comment]
Do you mean fine-tuning the meta-learner and base-learner or is it in reference to some other models?

**Comment by chunbolang** [comment]
I mean to fine-tune the meta-learner.

You might be interested in these two repositories, [RePRI](https://github.com/mboudiaf/RePRI-for-Few-Shot-Segmentation) and [CWT](https://github.com/zhiheLu/CWT-for-FSS).

**Comment by hazkaz** [comment]
Thank you for the tips and useful pointers.
