### ISSUE TITLE
Question on COCO experiments

### ISSUE THREAD

**Issue by milk-potato** [chunbolang/BAM#42]
Thank you for sharing your work!

We note that there are more than 13k pictures for every validation split in the coco dataset—however, only 1k iterations are set during testing, which may cause significant fluctuation of experimental results.

Compared with this, related works like HSnet, VAT, PFENet, and so on, all set more than 10k iterations during testing. So we replicated the experiments and followed all configs in your original with the sharing model parameters, except the number of the iterations set to 10k, in other words, the "test_num".

This is the result below:
![result](https://user-images.githubusercontent.com/111640221/185745230-eb604195-c241-4d5d-823c-8ca9de308f16.PNG)

Why is it set like this? Is there any other considerations？

**Comment by happycoding1996** [comment]
Same question. 1000 evaluation episodes on COCO20i make the testing results extremely not stable and probably not fair enough when compared with related works. I cannot make a valid comparison to show the effectiveness of the method with fluctuated results.

**Comment by chunbolang** [comment]
Hi, thanks for your interest!

Actually, most methods selected 1,000 episodes for testing, including the SOTA—[VAT](https://github.com/Seokju-Cho/Volumetric-Aggregation-Transformer/blob/f7558a1c9c89a8bb384238daf693827d293ad5dc/data/coco.py#L30) and [HSNet](https://github.com/juhongm999/hsnet/blob/main/data/coco.py#L30) (given below).

![$H{$LAE(KN~JXALW6ABBNH9](https://user-images.githubusercontent.com/41976180/195746706-e5762c52-0183-4dc5-a19a-20367d0edaad.png)

As far as I am concerned, 

- for verifying the effectiveness of the proposed **module**, the selection of 1,000 episodes with a fixed random seed is sufficient;
- for comparison with other advanced FSS **methods**, the introduction of a larger number of episodes (4k, 5k, or more) would ensure the stability of the results, however it is important to note that the other methods compared are likely to be based on the 1,000 episodes as well.

Incidentally, _testing the 1,000 episodes multiple times using different random seeds_ (ours) and _testing more episodes in a single run_ are both alternatives. 

Regards,

**Comment by milk-potato** [comment]
But the experimental results cannot be reproduced, and the fluctuation is more than 3% mIoU.

**Comment by chunbolang** [comment]
> But the experimental results cannot be reproduced, and the fluctuation is more than 3% mIoU.

Hi, sorry for the inconvenience!

Maybe you can refer to this [issue](https://github.com/chunbolang/BAM/issues/30#issuecomment-1167021820).

**Comment by milk-potato** [comment]
Thanks for your reply.
