### ISSUE TITLE
Problem about the implementation of Frobenius norms

### ISSUE THREAD

**Issue by Glutaredoxin** [chunbolang/BAM#49]
Hi, Lang!
The $\fi$ after Frobenius norms in the paper looks like just a number. But, in code, the weights of self.cls_merge seems adaptive and the dimension is torch.Size([1, 2, 1, 1]) with two parameters?
Maybe i do not understand the real meaning in the code, can you explain?
Sorry to bother you and thank you soooo much!

**Comment by chunbolang** [comment]
Sorry for the late reply.

`self.cls_merge` serves to fuse the background map generated by the meta-learner and the foreground map generated by the base-learner, so it has two parameters.

Best,

**Comment by Glutaredoxin** [comment]
I got it.

Thank you soooo much!

Best,
