### ISSUE TITLE
Questions about K-shot setting

### ISSUE THREAD

**Issue by includeYY** [chunbolang/BAM#5]
Thanks for your exciting job. I have some questions about the K-shot setting.
1. In Sec 4.4 you said `the smaller value of \psi indicates a greater contribution` but the Eqn 17 seems like  `the bigger value of \psi indicates a greater contribution`, which is obvious unexpected. An I miss something ?
2. In the implementation of K-shot setting, the value of `idx3` is just the `[0,1,2,3,4]` in 5-shot setting, which seems like useless. I really feel confuse about it.

**Comment by chunbolang** [comment]
@includeYY 
Hi,
thanks for your interest. 

1. `A small value indicates a greater contribution` is the desired result, while there are no additional constraints to facilitate this. For Eqn 17, this two-layer network could model negative correlation properties, if the learned weights contain _negative_ values.
2. This part of the code is to eliminate the effect of K-shot _order_ on the reweighting. It seems that the code is our _previous debug version_ and should be changed to:      
```
  val1, idx1 = est_val_total.sort(1)
  val2, idx2 = idx1.sort(1)
  weight = self.kshot_rw(val1)
  weight = weight.gather(1, idx2)
  weight_soft = torch.softmax(weight, 1)
```
Thank you for your correction and apologize for the inconvenience. 

Regards,
Chunbo

**Comment by includeYY** [comment]
Thanks for your reply!
