### ISSUE TITLE
The confusion about corr_query_mask

### ISSUE THREAD

**Issue by zhuolingli** [chunbolang/BAM#53]
Hi, thanks for your great work!
I'm confused by `corr_query_mask` in `BAM.py`, which is computed as the same as **prior mask**  proposed in  PFENet.
Such  `corr_query_mask` does not seem to be mentioned in the paper.  I wonder if it is introduced as a widely used trick?
Best wishes!

**Comment by chunbolang** [comment]
Hi, thanks for your attention!

Yes, it's a nice FSS technique that can improve certain performance with almost no change in structure.
Feel free to contact.

Best,
