### ISSUE TITLE
Some questions about training.

### ISSUE THREAD

**Issue by zhuolingli** [chunbolang/BAM#54]
Thank you for your awesome work.
I noticed that the weights of the resnet backbone, reorganized as `self.encoder`, are not frozen and are optimized during the first training phase.
However, in the second training stage, this encoder is abandoned, just using `self.learner_base (PSPNet_.ppm, PSPNet_.cls)` to extract the base output after the 4 original conv blocks of resnet.
I wonder if this `learner_base` is incompatible with the original resnet backbone during the second training and testing, because the `learner_base` has been co-optimized with `self.encoder` whose parameters are different from those of the original resnet backbone .   
Best,

**Comment by chunbolang** [comment]
Hi, thanks for your attention!

In the second training phase, the parameters of the backbone network, which the `base-learner` has trained, are shared for both learners. Please check this line of [code](https://github.com/chunbolang/BAM/blob/main/model/BAM.py#L71).

**Comment by zhuolingli** [comment]
Thanks for your reply! I appreciate it very much.
