### ISSUE TITLE
questions about the baseline

### ISSUE THREAD

**Issue by syp2ysy** [chunbolang/BAM#8]
Hello,  I have some questions about the baseline. Does the baseline only use the meta learner?  Some details about the baseline are not very clear, I hope you can give me some pointers. Thanks

**Comment by chunbolang** [comment]
@syp2ysy 
Hi, thanks for your interest.

Similar questions have been raised, please check [this issue](https://github.com/chunbolang/BAM/issues/2#issuecomment-1073161903).

Feel free to contact.

Best,
Chunbo
